dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
mono: none
language: csharp
solution: Pw.sln
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet restore
  - dotnet build ./src/Pw.sln -c Release 
  - dotnet test ./src/Pw.sln -c Release