dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
mono: none
dotnet: 2.2.203
language: csharp
solution: Pw.sln
install:
  - sudo snap alias dotnet-sdk.dotnet dotnet
before_script:
  - cd src
script:
  - dotnet restore
  - dotnet build
  - dotnet test