using System.IO;
using System.Linq;
using Pw.Elements;
using Pw.Elements.v155;
using AccStorageBlacklistConfig = Pw.Elements.v155.AccStorageBlacklistConfig;
using ArmorEssence = Pw.Elements.v155.ArmorEssence;
using ArmorMajorType = Pw.Elements.v155.ArmorMajorType;
using ArmorruneEssence = Pw.Elements.v155.ArmorruneEssence;
using ArmorruneSubType = Pw.Elements.v155.ArmorruneSubType;
using ArmorSubType = Pw.Elements.v155.ArmorSubType;
using AutohpEssence = Pw.Elements.v155.AutohpEssence;
using AutompEssence = Pw.Elements.v155.AutompEssence;
using BibleEssence = Pw.Elements.v155.BibleEssence;
using CharracterClassConfig = Pw.Elements.v155.CharracterClassConfig;
using ColorpickerEssence = Pw.Elements.v155.ColorpickerEssence;
using CongregateEssence = Pw.Elements.v155.CongregateEssence;
using CustomizedataEssence = Pw.Elements.v155.CustomizedataEssence;
using DamageruneEssence = Pw.Elements.v155.DamageruneEssence;
using DamageruneSubType = Pw.Elements.v155.DamageruneSubType;
using DecorationEssence = Pw.Elements.v155.DecorationEssence;
using DecorationMajorType = Pw.Elements.v155.DecorationMajorType;
using DecorationSubType = Pw.Elements.v155.DecorationSubType;
using DestroyingEssence = Pw.Elements.v155.DestroyingEssence;
using DoubleExpEssence = Pw.Elements.v155.DoubleExpEssence;
using DyeTicketEssence = Pw.Elements.v155.DyeTicketEssence;
using ElementEssence = Pw.Elements.v155.ElementEssence;
using ElementsData = Pw.Elements.v155.ElementsData;
using EnemyFactionConfig = Pw.Elements.v155.EnemyFactionConfig;
using EngraveEssence = Pw.Elements.v155.EngraveEssence;
using EngraveMajorType = Pw.Elements.v155.EngraveMajorType;
using EngraveSubType = Pw.Elements.v155.EngraveSubType;
using EquipmentAddon = Pw.Elements.v155.EquipmentAddon;
using FaceEmotionType = Pw.Elements.v155.FaceEmotionType;
using FaceExpressionEssence = Pw.Elements.v155.FaceExpressionEssence;
using FaceFalingEssence = Pw.Elements.v155.FaceFalingEssence;
using FaceHairEssence = Pw.Elements.v155.FaceHairEssence;
using FaceHairTextureMap = Pw.Elements.v155.FaceHairTextureMap;
using FaceMoustacheEssence = Pw.Elements.v155.FaceMoustacheEssence;
using FacepillEssence = Pw.Elements.v155.FacepillEssence;
using FacepillMajorType = Pw.Elements.v155.FacepillMajorType;
using FacepillSubType = Pw.Elements.v155.FacepillSubType;
using FaceShapeEssence = Pw.Elements.v155.FaceShapeEssence;
using FaceTextureEssence = Pw.Elements.v155.FaceTextureEssence;
using FaceThirdeyeEssence = Pw.Elements.v155.FaceThirdeyeEssence;
using FaceticketEssence = Pw.Elements.v155.FaceticketEssence;
using FaceticketMajorType = Pw.Elements.v155.FaceticketMajorType;
using FaceticketSubType = Pw.Elements.v155.FaceticketSubType;
using FactionBuildingEssence = Pw.Elements.v155.FactionBuildingEssence;
using FactionBuildingSubType = Pw.Elements.v155.FactionBuildingSubType;
using FactionFortressConfig = Pw.Elements.v155.FactionFortressConfig;
using FactionMaterialEssence = Pw.Elements.v155.FactionMaterialEssence;
using FashionEssence = Pw.Elements.v155.FashionEssence;
using FashionMajorType = Pw.Elements.v155.FashionMajorType;
using FashionSubType = Pw.Elements.v155.FashionSubType;
using FireworksEssence = Pw.Elements.v155.FireworksEssence;
using FlyswordEssence = Pw.Elements.v155.FlyswordEssence;
using GmGeneratorEssence = Pw.Elements.v155.GmGeneratorEssence;
using GmGeneratorType = Pw.Elements.v155.GmGeneratorType;
using GoblinEquipEssence = Pw.Elements.v155.GoblinEquipEssence;
using GoblinEquipType = Pw.Elements.v155.GoblinEquipType;
using GoblinEssence = Pw.Elements.v155.GoblinEssence;
using GoblinExppillEssence = Pw.Elements.v155.GoblinExppillEssence;
using GodEvilConvertConfig = Pw.Elements.v155.GodEvilConvertConfig;
using IncSkillAbilityEssence = Pw.Elements.v155.IncSkillAbilityEssence;
using LookInfoEssence = Pw.Elements.v155.LookInfoEssence;
using MaterialEssence = Pw.Elements.v155.MaterialEssence;
using MaterialMajorType = Pw.Elements.v155.MaterialMajorType;
using MaterialSubType = Pw.Elements.v155.MaterialSubType;
using MedicineEssence = Pw.Elements.v155.MedicineEssence;
using MedicineMajorType = Pw.Elements.v155.MedicineMajorType;
using MedicineSubType = Pw.Elements.v155.MedicineSubType;
using MineEssence = Pw.Elements.v155.MineEssence;
using MineType = Pw.Elements.v155.MineType;
using MonsterAddon = Pw.Elements.v155.MonsterAddon;
using MonsterEssence = Pw.Elements.v155.MonsterEssence;
using MonsterType = Pw.Elements.v155.MonsterType;
using MultiExpConfig = Pw.Elements.v155.MultiExpConfig;
using NpcBuyService = Pw.Elements.v155.NpcBuyService;
using NpcDecomposeService = Pw.Elements.v155.NpcDecomposeService;
using NpcEngraveService = Pw.Elements.v155.NpcEngraveService;
using NpcEquipbindService = Pw.Elements.v155.NpcEquipbindService;
using NpcEquipdestroyService = Pw.Elements.v155.NpcEquipdestroyService;
using NpcEquipundestroyService = Pw.Elements.v155.NpcEquipundestroyService;
using NpcEssence = Pw.Elements.v155.NpcEssence;
using NpcHealService = Pw.Elements.v155.NpcHealService;
using NpcIdentifyService = Pw.Elements.v155.NpcIdentifyService;
using NpcInstallService = Pw.Elements.v155.NpcInstallService;
using NpcMakeService = Pw.Elements.v155.NpcMakeService;
using NpcPetforgetskillService = Pw.Elements.v155.NpcPetforgetskillService;
using NpcPetlearnskillService = Pw.Elements.v155.NpcPetlearnskillService;
using NpcPetnameService = Pw.Elements.v155.NpcPetnameService;
using NpcProxyService = Pw.Elements.v155.NpcProxyService;
using NpcRandpropService = Pw.Elements.v155.NpcRandpropService;
using NpcRepairService = Pw.Elements.v155.NpcRepairService;
using NpcResetpropService = Pw.Elements.v155.NpcResetpropService;
using NpcSellService = Pw.Elements.v155.NpcSellService;
using NpcSkillService = Pw.Elements.v155.NpcSkillService;
using NpcStorageService = Pw.Elements.v155.NpcStorageService;
using NpcTalkService = Pw.Elements.v155.NpcTalkService;
using NpcTaskInService = Pw.Elements.v155.NpcTaskInService;
using NpcTaskMatterService = Pw.Elements.v155.NpcTaskMatterService;
using NpcTaskOutService = Pw.Elements.v155.NpcTaskOutService;
using NpcTransmitService = Pw.Elements.v155.NpcTransmitService;
using NpcTransportService = Pw.Elements.v155.NpcTransportService;
using NpcType = Pw.Elements.v155.NpcType;
using NpcUninstallService = Pw.Elements.v155.NpcUninstallService;
using NpcWarTowerbuildService = Pw.Elements.v155.NpcWarTowerbuildService;
using ParamAdjustConfig = Pw.Elements.v155.ParamAdjustConfig;
using PetEggEssence = Pw.Elements.v155.PetEggEssence;
using PetEssence = Pw.Elements.v155.PetEssence;
using PetFaceticketEssence = Pw.Elements.v155.PetFaceticketEssence;
using PetFoodEssence = Pw.Elements.v155.PetFoodEssence;
using PetType = Pw.Elements.v155.PetType;
using PlayerActionInfoConfig = Pw.Elements.v155.PlayerActionInfoConfig;
using PlayerLevelexpConfig = Pw.Elements.v155.PlayerLevelexpConfig;
using PlayerSecondlevelConfig = Pw.Elements.v155.PlayerSecondlevelConfig;
using ProjectileEssence = Pw.Elements.v155.ProjectileEssence;
using ProjectileType = Pw.Elements.v155.ProjectileType;
using QuiverEssence = Pw.Elements.v155.QuiverEssence;
using QuiverSubType = Pw.Elements.v155.QuiverSubType;
using RandpropEssence = Pw.Elements.v155.RandpropEssence;
using RandpropType = Pw.Elements.v155.RandpropType;
using RecipeEssence = Pw.Elements.v155.RecipeEssence;
using RecipeMajorType = Pw.Elements.v155.RecipeMajorType;
using RecipeSubType = Pw.Elements.v155.RecipeSubType;
using RefineTicketEssence = Pw.Elements.v155.RefineTicketEssence;
using RevivescrollEssence = Pw.Elements.v155.RevivescrollEssence;
using SellCertificateEssence = Pw.Elements.v155.SellCertificateEssence;
using SharpenerEssence = Pw.Elements.v155.SharpenerEssence;
using SkillmatterEssence = Pw.Elements.v155.SkillmatterEssence;
using SkilltomeEssence = Pw.Elements.v155.SkilltomeEssence;
using SkilltomeSubType = Pw.Elements.v155.SkilltomeSubType;
using SpeakerEssence = Pw.Elements.v155.SpeakerEssence;
using StoneEssence = Pw.Elements.v155.StoneEssence;
using StoneSubType = Pw.Elements.v155.StoneSubType;
using SuiteEssence = Pw.Elements.v155.SuiteEssence;
using TargetItemEssence = Pw.Elements.v155.TargetItemEssence;
using TaskdiceEssence = Pw.Elements.v155.TaskdiceEssence;
using TaskmatterEssence = Pw.Elements.v155.TaskmatterEssence;
using TasknormalmatterEssence = Pw.Elements.v155.TasknormalmatterEssence;
using TossmatterEssence = Pw.Elements.v155.TossmatterEssence;
using TownscrollEssence = Pw.Elements.v155.TownscrollEssence;
using TransmitscrollEssence = Pw.Elements.v155.TransmitscrollEssence;
using UnionscrollEssence = Pw.Elements.v155.UnionscrollEssence;
using UpgradeProductionConfig = Pw.Elements.v155.UpgradeProductionConfig;
using WarTankcallinEssence = Pw.Elements.v155.WarTankcallinEssence;
using WeaponEssence = Pw.Elements.v155.WeaponEssence;
using WeaponMajorType = Pw.Elements.v155.WeaponMajorType;
using WeaponSubType = Pw.Elements.v155.WeaponSubType;
using WeddingBookcardEssence = Pw.Elements.v155.WeddingBookcardEssence;
using WeddingConfig = Pw.Elements.v155.WeddingConfig;
using WeddingInvitecardEssence = Pw.Elements.v155.WeddingInvitecardEssence;
using WikiTabooConfig = Pw.Elements.v155.WikiTabooConfig;
using WingmanwingEssence = Pw.Elements.v155.WingmanwingEssence;

namespace Pw.ElementsYamlConverter
{
    public class YamlImporter
    {
        private readonly YamlSerializer _yamlSerializer;

        public YamlImporter(YamlSerializer yamlSerializer)
        {
            _yamlSerializer = yamlSerializer;
        }

        public ElementsData Import(string directory)
        {
            var elements = new ElementsData();

            elements.ElementsDataFileInfo = ImportElementsDataFileInfo();
            elements.EquipmentAddons = ImportList<EquipmentAddon>();
            elements.WeaponMajorTypes = ImportList<WeaponMajorType>();
            elements.WeaponSubTypes = ImportList<WeaponSubType>();
            elements.WeaponEssences = ImportList<WeaponEssence>();
            elements.ArmorMajorTypes = ImportList<ArmorMajorType>();
            elements.ArmorSubTypes = ImportList<ArmorSubType>();
            elements.ArmorEssences = ImportList<ArmorEssence>();
            elements.DecorationMajorTypes = ImportList<DecorationMajorType>();
            elements.DecorationSubTypes = ImportList<DecorationSubType>();
            elements.DecorationEssences = ImportList<DecorationEssence>();
            elements.MedicineMajorTypes = ImportList<MedicineMajorType>();
            elements.MedicineSubTypes = ImportList<MedicineSubType>();
            elements.MedicineEssences = ImportList<MedicineEssence>();
            elements.MaterialMajorTypes = ImportList<MaterialMajorType>();
            elements.MaterialSubTypes = ImportList<MaterialSubType>();
            elements.MaterialEssences = ImportList<MaterialEssence>();
            elements.DamageruneSubTypes = ImportList<DamageruneSubType>();
            elements.DamageruneEssences = ImportList<DamageruneEssence>();
            elements.ArmorruneSubTypes = ImportList<ArmorruneSubType>();
            elements.ArmorruneEssences = ImportList<ArmorruneEssence>();
            elements.SkilltomeSubTypes = ImportList<SkilltomeSubType>();
            elements.SkilltomeEssences = ImportList<SkilltomeEssence>();
            elements.FlyswordEssences = ImportList<FlyswordEssence>();
            elements.WingmanwingEssences = ImportList<WingmanwingEssence>();
            elements.TownscrollEssences = ImportList<TownscrollEssence>();
            elements.UnionscrollEssences = ImportList<UnionscrollEssence>();
            elements.RevivescrollEssences = ImportList<RevivescrollEssence>();
            elements.ElementEssences = ImportList<ElementEssence>();
            elements.TaskmatterEssences = ImportList<TaskmatterEssence>();
            elements.TossmatterEssences = ImportList<TossmatterEssence>();
            elements.ProjectileTypes = ImportList<ProjectileType>();
            elements.ProjectileEssences = ImportList<ProjectileEssence>();
            elements.QuiverSubTypes = ImportList<QuiverSubType>();
            elements.QuiverEssences = ImportList<QuiverEssence>();
            elements.StoneSubTypes = ImportList<StoneSubType>();
            elements.StoneEssences = ImportList<StoneEssence>();
            elements.MonsterAddons = ImportList<MonsterAddon>();
            elements.MonsterTypes = ImportList<MonsterType>();
            elements.MonsterEssences = ImportList<MonsterEssence>();
            elements.NpcTalkServices = ImportList<NpcTalkService>();
            elements.NpcSellServices = ImportList<NpcSellService>();
            elements.NpcBuyServices = ImportList<NpcBuyService>();
            elements.NpcRepairServices = ImportList<NpcRepairService>();
            elements.NpcInstallServices = ImportList<NpcInstallService>();
            elements.NpcUninstallServices = ImportList<NpcUninstallService>();
            elements.NpcTaskInServices = ImportList<NpcTaskInService>();
            elements.NpcTaskOutServices = ImportList<NpcTaskOutService>();
            elements.NpcTaskMatterServices = ImportList<NpcTaskMatterService>();
            elements.NpcSkillServices = ImportList<NpcSkillService>();
            elements.NpcHealServices = ImportList<NpcHealService>();
            elements.NpcTransmitServices = ImportList<NpcTransmitService>();
            elements.NpcTransportServices = ImportList<NpcTransportService>();
            elements.NpcProxyServices = ImportList<NpcProxyService>();
            elements.NpcStorageServices = ImportList<NpcStorageService>();
            elements.NpcMakeServices = ImportList<NpcMakeService>();
            elements.NpcDecomposeServices = ImportList<NpcDecomposeService>();
            elements.NpcTypes = ImportList<NpcType>();
            elements.NpcEssences = ImportList<NpcEssence>();
            elements.TalkProcs = ImportList<TalkProc>();
            elements.FaceTextureEssences = ImportList<FaceTextureEssence>();
            elements.FaceShapeEssences = ImportList<FaceShapeEssence>();
            elements.FaceEmotionTypes = ImportList<FaceEmotionType>();
            elements.FaceExpressionEssences = ImportList<FaceExpressionEssence>();
            elements.FaceHairEssences = ImportList<FaceHairEssence>();
            elements.FaceMoustacheEssences = ImportList<FaceMoustacheEssence>();
            elements.ColorpickerEssences = ImportList<ColorpickerEssence>();
            elements.CustomizedataEssences = ImportList<CustomizedataEssence>();
            elements.RecipeMajorTypes = ImportList<RecipeMajorType>();
            elements.RecipeSubTypes = ImportList<RecipeSubType>();
            elements.RecipeEssences = ImportList<RecipeEssence>();
            elements.EnemyFactionConfigs = ImportList<EnemyFactionConfig>();
            elements.CharracterClassConfigs = ImportList<CharracterClassConfig>();
            elements.ParamAdjustConfigs = ImportList<ParamAdjustConfig>();
            elements.PlayerActionInfoConfigs = ImportList<PlayerActionInfoConfig>();
            elements.TaskdiceEssences = ImportList<TaskdiceEssence>();
            elements.TasknormalmatterEssences = ImportList<TasknormalmatterEssence>();
            elements.FaceFalingEssences = ImportList<FaceFalingEssence>();
            elements.PlayerLevelexpConfigs = ImportList<PlayerLevelexpConfig>();
            elements.MineTypes = ImportList<MineType>();
            elements.MineEssences = ImportList<MineEssence>();
            elements.NpcIdentifyServices = ImportList<NpcIdentifyService>();
            elements.FashionMajorTypes = ImportList<FashionMajorType>();
            elements.FashionSubTypes = ImportList<FashionSubType>();
            elements.FashionEssences = ImportList<FashionEssence>();
            elements.FaceticketMajorTypes = ImportList<FaceticketMajorType>();
            elements.FaceticketSubTypes = ImportList<FaceticketSubType>();
            elements.FaceticketEssences = ImportList<FaceticketEssence>();
            elements.FacepillMajorTypes = ImportList<FacepillMajorType>();
            elements.FacepillSubTypes = ImportList<FacepillSubType>();
            elements.FacepillEssences = ImportList<FacepillEssence>();
            elements.SuiteEssences = ImportList<SuiteEssence>();
            elements.GmGeneratorTypes = ImportList<GmGeneratorType>();
            elements.GmGeneratorEssences = ImportList<GmGeneratorEssence>();
            elements.PetTypes = ImportList<PetType>();
            elements.PetEssences = ImportList<PetEssence>();
            elements.PetEggEssences = ImportList<PetEggEssence>();
            elements.PetFoodEssences = ImportList<PetFoodEssence>();
            elements.PetFaceticketEssences = ImportList<PetFaceticketEssence>();
            elements.FireworksEssences = ImportList<FireworksEssence>();
            elements.Fireworks2Essences = ImportList<Fireworks2Essence>();
            elements.FixPositionTransmitEssences = ImportList<FixPositionTransmitEssence>();
            elements.WarTankcallinEssences = ImportList<WarTankcallinEssence>();
            elements.NpcWarTowerbuildServices = ImportList<NpcWarTowerbuildService>();
            elements.PlayerSecondlevelConfigs = ImportList<PlayerSecondlevelConfig>();
            elements.NpcResetpropServices = ImportList<NpcResetpropService>();
            elements.NpcPetnameServices = ImportList<NpcPetnameService>();
            elements.NpcPetlearnskillServices = ImportList<NpcPetlearnskillService>();
            elements.NpcPetforgetskillServices = ImportList<NpcPetforgetskillService>();
            elements.SkillmatterEssences = ImportList<SkillmatterEssence>();
            elements.RefineTicketEssences = ImportList<RefineTicketEssence>();
            elements.DestroyingEssences = ImportList<DestroyingEssence>();
            elements.NpcEquipbindServices = ImportList<NpcEquipbindService>();
            elements.NpcEquipdestroyServices = ImportList<NpcEquipdestroyService>();
            elements.NpcEquipundestroyServices = ImportList<NpcEquipundestroyService>();
            elements.BibleEssences = ImportList<BibleEssence>();
            elements.SpeakerEssences = ImportList<SpeakerEssence>();
            elements.AutompEssences = ImportList<AutompEssence>();
            elements.AutohpEssences = ImportList<AutohpEssence>();
            elements.DoubleExpEssences = ImportList<DoubleExpEssence>();
            elements.TransmitscrollEssences = ImportList<TransmitscrollEssence>();
            elements.DyeTicketEssences = ImportList<DyeTicketEssence>();
            elements.GoblinEssences = ImportList<GoblinEssence>();
            elements.GoblinEquipTypes = ImportList<GoblinEquipType>();
            elements.GoblinEquipEssences = ImportList<GoblinEquipEssence>();
            elements.GoblinExppillEssences = ImportList<GoblinExppillEssence>();
            elements.SellCertificateEssences = ImportList<SellCertificateEssence>();
            elements.TargetItemEssences = ImportList<TargetItemEssence>();
            elements.LookInfoEssences = ImportList<LookInfoEssence>();
            elements.UpgradeProductionConfigs = ImportList<UpgradeProductionConfig>();
            elements.AccStorageBlacklistConfigs = ImportList<AccStorageBlacklistConfig>();
            elements.FaceHairTextureMaps = ImportList<FaceHairTextureMap>();
            elements.MultiExpConfigs = ImportList<MultiExpConfig>();
            elements.IncSkillAbilityEssences = ImportList<IncSkillAbilityEssence>();
            elements.GodEvilConvertConfigs = ImportList<GodEvilConvertConfig>();
            elements.WeddingConfigs = ImportList<WeddingConfig>();
            elements.WeddingBookcardEssences = ImportList<WeddingBookcardEssence>();
            elements.WeddingInvitecardEssences = ImportList<WeddingInvitecardEssence>();
            elements.SharpenerEssences = ImportList<SharpenerEssence>();
            elements.FaceThirdeyeEssences = ImportList<FaceThirdeyeEssence>();
            elements.FactionFortressConfigs = ImportList<FactionFortressConfig>();
            elements.FactionBuildingSubTypes = ImportList<FactionBuildingSubType>();
            elements.FactionBuildingEssences = ImportList<FactionBuildingEssence>();
            elements.FactionMaterialEssences = ImportList<FactionMaterialEssence>();
            elements.CongregateEssences = ImportList<CongregateEssence>();
            elements.EngraveMajorTypes = ImportList<EngraveMajorType>();
            elements.EngraveSubTypes = ImportList<EngraveSubType>();
            elements.EngraveEssences = ImportList<EngraveEssence>();
            elements.NpcEngraveServices = ImportList<NpcEngraveService>();
            elements.NpcRandpropServices = ImportList<NpcRandpropService>();
            elements.RandpropTypes = ImportList<RandpropType>();
            elements.RandpropEssences = ImportList<RandpropEssence>();
            elements.WikiTabooConfigs = ImportList<WikiTabooConfig>();
            elements.ForceConfigs = ImportList<ForceConfig>();
            elements.ForceTokenEssences = ImportList<ForceTokenEssence>();
            elements.NpcForceServices = ImportList<NpcForceService>();
            elements.PlayerDeathDropConfigs = ImportList<PlayerDeathDropConfig>();
            elements.DynskillequipEssences = ImportList<DynskillequipEssence>();
            elements.ConsumePointsConfigs = ImportList<ConsumePointsConfig>();
            elements.OnlineAwardsConfigs = ImportList<OnlineAwardsConfig>();
            elements.CountryConfigs = ImportList<CountryConfig>();
            elements.GmActivityConfigs = ImportList<GmActivityConfig>();
            elements.FashionWeaponConfigs = ImportList<FashionWeaponConfig>();
            elements.PetEvolveConfigs = ImportList<PetEvolveConfig>();
            elements.PetEvolvedSkillConfigs = ImportList<PetEvolvedSkillConfig>();
            elements.MoneyConvertibleEssences = ImportList<MoneyConvertibleEssence>();
            elements.StoneChangeRecipeTypes = ImportList<StoneChangeRecipeType>();
            elements.StoneChangeRecipes = ImportList<StoneChangeRecipe>();
            elements.MeridianConfigs = ImportList<MeridianConfig>();
            elements.PetEvolvedSkillRandConfigs = ImportList<PetEvolvedSkillRandConfig>();
            elements.AutotaskDisplayConfigs = ImportList<AutotaskDisplayConfig>();
            elements.TouchShopConfigs = ImportList<TouchShopConfig>();
            elements.TitleConfigs = ImportList<TitleConfig>();
            elements.ComplexTitleConfigs = ImportList<ComplexTitleConfig>();
            elements.MonsterSpiritEssences = ImportList<MonsterSpiritEssence>();
            elements.PlayerSpiritConfigs = ImportList<PlayerSpiritConfig>();
            elements.PlayerReincarnationConfigs = ImportList<PlayerReincarnationConfig>();
            elements.HistoryStageConfigs = ImportList<HistoryStageConfig>();
            elements.HistoryAdvanceConfigs = ImportList<HistoryAdvanceConfig>();
            elements.AutoteamConfigs = ImportList<AutoteamConfig>();
            elements.PlayerRealmConfigs = ImportList<PlayerRealmConfig>();
            elements.ChariotConfigs = ImportList<ChariotConfig>();
            elements.ChariotWarConfigs = ImportList<ChariotWarConfig>();
            elements.PokerLevelexpConfigs = ImportList<PokerLevelexpConfig>();
            elements.PokerSuiteEssences = ImportList<PokerSuiteEssence>();
            elements.PokerDiceEssences = ImportList<PokerDiceEssence>();
            elements.PokerSubTypes = ImportList<PokerSubType>();
            elements.PokerEssences = ImportList<PokerEssence>();
            elements.TokenShopConfigs = ImportList<TokenShopConfig>();
            elements.ShopTokenEssences = ImportList<ShopTokenEssence>();
            elements.GtConfigs = ImportList<GtConfig>();
            elements.RandShopConfigs = ImportList<RandShopConfig>();
            elements.ProfitTimeConfigs = ImportList<ProfitTimeConfig>();
            elements.FactionPvpConfigs = ImportList<FactionPvpConfig>();
            elements.UniversalTokenEssences = ImportList<UniversalTokenEssence>();
            elements.TaskListConfigs = ImportList<TaskListConfig>();
            elements.TaskDiceByWeightConfigs = ImportList<TaskDiceByWeightConfig>();
            elements.FashionSuiteEssences = ImportList<FashionSuiteEssence>();
            elements.FashionBestColorConfigs = ImportList<FashionBestColorConfig>();
            elements.SignAwardConfigs = ImportList<SignAwardConfig>();
            elements.AstrolabeEssences = ImportList<AstrolabeEssence>();
            elements.AstrolabeRandomAddonEssences = ImportList<AstrolabeRandomAddonEssence>();
            elements.AstrolabeIncInnerPointValueEssences = ImportList<AstrolabeIncInnerPointValueEssence>();
            elements.AstrolabeIncExpEssences = ImportList<AstrolabeIncExpEssence>();
            elements.ItemPackageByProfessionEssences = ImportList<ItemPackageByProfessionEssence>();
            elements.AstrolabeLevelexpConfigs = ImportList<AstrolabeLevelexpConfig>();
            elements.AstrolabeAddonRandomConfigs = ImportList<AstrolabeAddonRandomConfig>();
            elements.AstrolabeAppearanceConfigs = ImportList<AstrolabeAppearanceConfig>();
            elements.EquipMakeHoleConfigs = ImportList<EquipMakeHoleConfig>();
            elements.SoloTowerChallengeLevelConfigs = ImportList<SoloTowerChallengeLevelConfig>();
            elements.SoloTowerChallengeAwardPageConfigs = ImportList<SoloTowerChallengeAwardPageConfig>();
            elements.SoloTowerChallengeAwardListConfigs = ImportList<SoloTowerChallengeAwardListConfig>();
            elements.SoloTowerChallengeScoreCostConfigs = ImportList<SoloTowerChallengeScoreCostConfig>();
            elements.MnfactionWarConfigs = ImportList<MnfactionWarConfig>();
            elements.NpcCrossServerServices = ImportList<NpcCrossServerService>();
            elements.HomeConfigs = ImportList<HomeConfig>();
            elements.HomeProductsConfigs = ImportList<HomeProductsConfig>();
            elements.HomeResourceProduceConfigs = ImportList<HomeResourceProduceConfig>();
            elements.HomeFormulasProduceRecipes = ImportList<HomeFormulasProduceRecipe>();
            elements.HomeFormulasItemEssences = ImportList<HomeFormulasItemEssence>();
            elements.HomeProduceServiceConfigs = ImportList<HomeProduceServiceConfig>();
            elements.HomeFactoryConfigs = ImportList<HomeFactoryConfig>();
            elements.HomeItemMajorTypes = ImportList<HomeItemMajorType>();
            elements.HomeItemSubTypes = ImportList<HomeItemSubType>();
            elements.HomeItemEntities = ImportList<HomeItemEntity>();
            elements.HomeFormulasProduceMajorTypes = ImportList<HomeFormulasProduceMajorType>();
            elements.HomeFormulasProduceSubTypes = ImportList<HomeFormulasProduceSubType>();
            elements.HomeFormulasItemMajorTypes = ImportList<HomeFormulasItemMajorType>();
            elements.HomeFormulasItemSubTypes = ImportList<HomeFormulasItemSubType>();
            elements.HomeStorageTaskConfigs = ImportList<HomeStorageTaskConfig>();
            elements.WishTributeEssences = ImportList<WishTributeEssence>();
            elements.RedPacketPaperEssences = ImportList<RedPacketPaperEssence>();


            return elements;

            T[] ImportList<T>() where T : IElementsType
            {
                var path = TypeToPath<T>();
                var list = Deserialize<T[]>(path);
                elements.Lists.Add(typeof(T).Name, list.Cast<IElementsType>().ToArray());
                return list;
            }

            ElementsDataFileInfo ImportElementsDataFileInfo()
            {
                var path = TypeToPath<ElementsDataFileInfo>();
                return Deserialize<ElementsDataFileInfo>(path);
            }

            T Deserialize<T>(string path)
            {
                var file = File.ReadAllBytes(path);
                using var stream = new MemoryStream(file);
                return _yamlSerializer.DeSerialize<T>(stream);
            }

            string TypeToPath<T>()
            {
                var listName = typeof(T).Name;
                var path = Path.Combine(directory, $"{listName}.yaml");
                return path;
            }
        }
    }
}
